### PR TITLE
movie-database-complete

### PR DESCRIPTION
**Pull request by swaff-y**
_If you had no problems you can just leave it empty_
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
       7
- Was there anything that you struggled with?
      reading the api notes after a long day

- Roughly how long did it take?
      4hours

### CODE REVIEW

**Comment by ispzz** [comment]
I have no idea how you were able to take in more info but great work getting the cast info too!

**Comment by swaff-y** [comment]
Thanks Zara, 

I’m not sure if replying with an email works? 🤷‍♂️

Kind Regards,
Kyle Swaffield
kyle@swaff.id.au
0450493936

**Comment by ispzz** [comment]
Replying through email does work!!

**Comment by swaff-y** [comment]
Fantastic 😁 

Kind Regards,
Kyle Swaffield
kyle@swaff.id.au
0450493936

**Pull request merged**
